import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-6.png",
    Newest:false,
    FastDelievery:false,
    rating:4.2,
    price: "67999",
    categoryName: "Watch",
  },
  {
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-1.jpg",
    Newest:true,
    FastDelievery:true,
    rating:5.5,
    price: "5000",
    categoryName: "WatchBand",
  }, 
  {
    _id: uuid(),
    title: "Phone",
    image: "/product-images/Phone/iphones-2-img.png",
    Newest:true,
    FastDelievery:true,
    rating:1.5,
    price: "30000",
    categoryName: "Phone",
  },
  {
    _id: uuid(),
    title: "Airpod",
   
    image: "/product-images/AirPods/airpods-2.png",
    Newest:true,
    FastDelievery:false,
    rating:3.5,
    price: "1999",
    categoryName: "AirPods",
  },
  {
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-8.jpg",
    Newest:true,
    FastDelievery:true,
    rating:2.5,
    price: "5000",
    categoryName: "WatchBand",
  },{
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-9.jpg",
    Newest:true,
    FastDelievery:true,
    rating:4.5,
    price: "5000",
    categoryName: "WatchBand",
  },{
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-10.jpg",
    Newest:true,
    FastDelievery:true,
    rating:1,
    price: "5000",
    categoryName: "WatchBand",
  },
 {
    _id: uuid(),
    title: "Phone",
    image: "/product-images/Phone/iphones-2-img.png",
    Newest:true,
    FastDelievery:true,
    rating:2.3,
    price: "9,99.999",
    categoryName: "Phone",
  },
 
  {
    _id: uuid(),
    title: "Airpod",
   
    image: "/product-images/AirPods/images (1).jpg",
    Newest:true,
    FastDelievery:false,
    rating:4.2,
    price: "5699",
    categoryName: "AirPods",
  },{
    _id: uuid(),
    title: "Watch",
    image: "/product-images/watches/watch-case-1.png",
    Newest:false,
    FastDelievery:false,
    rating:2,
    price: "5000",
    categoryName: "Watch",
  },
  {
    _id: uuid(),
    title: "out of stock",
   
    image: "/product-images/AirPods/image2.jpg",
    Newest:true,
    FastDelievery:false,
    rating:2,
    price: "1999999",
    categoryName: "Newest",
  },
   {
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-2.png",
    Newest:false,
    FastDelievery:false,
    rating:3,
    price: "400000",
    categoryName: "Watch",
  }, {
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-3.png",
    Newest:false,
    FastDelievery:false,
    rating:3,
    price: "4999",
    categoryName: "Watch",
  },
  {
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-4.png",
    Newest:false,
    FastDelievery:false,
    rating:4.5,
    price: "7999",
    categoryName: "Watch",
  },
  
  {
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-7.png",
    Newest:false,
    FastDelievery:false,
    rating:5,
    price: "10999",
    categoryName: "Watch",
  },
  {
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-8.png",
    Newest:false,
    FastDelievery:false,
    rating:5,
    price: "999",
    categoryName: "Watch",
  },
  {
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-9.png",
    Newest:false,
    FastDelievery:false,
    rating:5,
    price: "199",
    categoryName: "Watch",
  },{
    _id: uuid(),
    title: " Watch",
    image: "/product-images/watches/watch-case-10.png",
    Newest:false,
    FastDelievery:false,
    rating:4,
    price: "99",
    categoryName: "Watch",
  },
  {
    _id: uuid(),
    title: "Free Reward",
  
    image: "/product-images/watches/watch-case-5.png",
    rating:4,
    price: "000",
    categoryName: "FastDelievery",
  },{
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-2.jpg",
    Newest:true,
    FastDelievery:true,
    rating:2,
    price: "5000000",
    categoryName: "WatchBand",
  },{
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-3.jpg",
    Newest:true,
    FastDelievery:true,
    rating:1.3,
    price: "499",
    categoryName: "WatchBand",
  },{
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-4.jpg",
    Newest:true,
    FastDelievery:true,
    rating:5,
    price: "499990",
    categoryName: "WatchBand",
  },{
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-5.jpg",
    Newest:true,
    FastDelievery:true,
    rating:5,
    price: "6800",
    categoryName: "WatchBand",
  },
  {
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-6.jpg",
    Newest:true,
    FastDelievery:true,
    rating:5,
    price: "100000",
    categoryName: "WatchBand",
  },{
    _id: uuid(),
    title: "watch-band",
    image: "/product-images/watches/watch-band-7.jpg",
    Newest:true,
    FastDelievery:true,
    rating:5,
    price: "50000",
    categoryName: "WatchBand",
  },
  {
    _id: uuid(),
    title: "Free Reward",
   
    image: "/product-images/AirPods/reward.jpg",
    rating:3,
    price: "000",
    categoryName: "FastDelievery",
  },
  {
    _id: uuid(),
    title: "Free Reward",
   
    image: "/product-images/AirPods/reward.jpg",
    rating:3,
    price: "000",
    categoryName: "Newest",
  },
  {
    _id: uuid(),
    title: "Free Reward",
   
    image: "/product-images/Phone/iphones-2-img.png",
    rating:1,
    price: "000",
    categoryName: "FastDelievery",
  },
];
